language: node_js
node_js:
  - "12"

script:
  - yarn lint
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: npm
  edge: true
  email: audun@rundberg.no
  src: dist
  api_key:
    secure: bD28jHpQSOmLVhGZE+AJGeUDDpDA+kCMC9NNP3rO5DmOtkttfWbvf1beg0aNNFp3U7VXsJRCy2efAR2ft3cEh1SzWkEGiOT1XM2YKJDXo2EljPxh9Ta8W+Fg6Swa0yut3AR5GRcSvnIUv13MVOrUpoC+fCkY8rHX0d4oMfKxjTvFCelKKBSSxuBUM4IgynTHojIDglMyYYSxDLW8bOWCSSYfmhvneLFB7ME9GFWcL91Z8+6mlEscNk9RJaS6S+y+hIe6cXfRQGpBNuzqGuQBK0TRMxdqWWFnuVf21e3UmvT075679hNEBy7xeRKSeZyWsBZ815tjtikmKKHtC8fYZX0GHITKjR/dKtR+poAkSQkdLwDEaR21QUrCkYne1lSCuLKmk6ppwu+n0lOfp7nhHl1NZD4p6vblDrAdhdnil3g/l9H0w59LrGC1sIvhV3kz/OUcUXFplaDg0iMYtT93m3M+rV3MCyiWD+NefTfubXRmIjvsrDC5anjDozqngDfN4zO8PWE2H0ak62xB+a3qtR5cjMmf4SE0K+M6CWsJWC6m4LBcRQqj8igOIUtBdSc6JNzFV3s0S61CrGzKhqqm6/E7602H80naTE/nnJivXVOgRJBAf8aKTsb05skxdrwhMxQxUhXIBE+4FSFW5XSknnZCMORWPb6DxbLgXr9XXNc=
  skip_cleanup: true
  on:
    tags: true
    repo: audunru/gatsby-source-remote-file
