language: node_js
node_js:
  - '12'

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: npm release
      if: tag IS present
      node_js: '12'
      script: yarn build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
        edge: true
