steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: "12"
      registry-url: "https://registry.npmjs.org"
  - run: yarn install
  - run: yarn validate
  - if: startsWith(github.ref, 'refs/tags/v')
    run: yarn publish dist
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
