name: Validate and publish

on: [push, pull_request]

jobs:
  validate-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
